[keyboard]
bindings = [{ key = "F11", action = "ToggleFullscreen" }]

[font]
normal = { family = "SauceCodePro Nerd Font", style = "Medium" }
bold = { style = "Medium" }
bold_italic = { style = "Italic" }
size = 10
